import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

const config: Config = {
  title: "Distributed Async Await",
  tagline: "Specification for a holistic cloud programming model.",
  favicon: "img/daa-logo.png",

  // Set the production url of your site here
  url: "https://distributed-async-await.io",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "resonatehq", // Usually your GitHub org/user name.
  projectName: "distributed-async-await.io", // Usually your repo name.

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          routeBasePath: "/", // Serve the docs at the site's root (ref: https://docusaurus.io/docs/next/docs-introduction#home-page-docs)
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            "https://github.com/resonatehq/distributed-async-await.io/tree/main/",
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
          breadcrumbs: true,
          exclude: ["**/code/**"],
        },
        blog: false,
        theme: {
          customCss: [
            "./static/css/custom.css",
            "./static/css/boxicons.min.css",
          ],
        },
        gtag: {
          trackingID: "G-0660YY8LZF",
          anonymizeIP: true,
        },
      } satisfies Preset.Options,
    ],
  ],
  scripts: [
    {
      src: "/scripts/fullstory.js",
      async: true,
    },
    {
      src: "https://widget.kapa.ai/kapa-widget.bundle.js",
      "data-website-id": "0f3cf17e-47fa-427a-b0fd-464d33f0bb16",
      "data-project-name": "ask ai",
      "data-project-color": "#f98c39",
      "data-project-logo": "/img/daa-logo.png",
      "data-user-analytics-fingerprint-enabled": "true",
      "data-button-hide": "true",
      "data-modal-override-open-class-search": "search-echo",
      "data-modal-title-ask-ai": "AI Assistant",
      "data-modal-border-radius": "0px",
      "data-modal-title-search": "Search",
      "data-modal-image": "/img/daa-logo.png",
      "data-modal-disclaimer":
        "As an AI Assistant, I have access to the entire Distributed Async Await specification as well as other Resonate HQ resources. Responses are generated by combining sources to provide the best possible answer. However, sometimes I may make a mistake, so please use your best judgement. Help me improve by providing a thumbs up or thumbs down after each response.",
      "data-modal-ask-ai-input-placeholder":
        "Ask me a question about Distributed Async Await",
      "data-modal-open-on-command-k": "true",

      "data-modal-example-questions-title": "For example...",
      "data-search-mode-enabled": "true",
      "data-switch-show-icons": "true",
      "data-switch-color": "#f98c39",
      async: true,
    },
    {
      src: "/scripts/cookiebanner.js",
      async: true,
    },
  ],
  stylesheets: [
    {
      href: "https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap",
      rel: "stylesheet",
    },
    {
      href: "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap",
      rel: "stylesheet",
    },
  ],

  themeConfig: {
    image: "img/echo.png", // used for link previews
    colorMode: {
      defaultMode: "light",
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    navbar: {
      title: "Distributed Async Await",
      logo: {
        alt: "Distributed Async Await logo",
        src: "img/daa-logo.png",
        href: "/",
        target: "_self",
      },
      items: [
        {
          href: "https://resonatehq.io/discord",
          html: '<i class="bx bx-md bxl-discord"></i>',
          position: "right",
        },
      ],
    },

    footer: {
      style: "light",
      links: [
        {
          html: `
            <a href="https://resonatehq.io/discord" target="_blank" rel="noopener noreferrer" aria-label="Resonate HQ Discord">
              <i class="bx bx-sm bxl-discord"></i>
            </a>
          `,
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} ResonateHQ, Inc.`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
